# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: sobel_service.proto
# Protobuf Python Version: 6.31.1
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import runtime_version as _runtime_version
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
_runtime_version.ValidateProtobufRuntimeVersion(
    _runtime_version.Domain.PUBLIC,
    6,
    31,
    1,
    '',
    'sobel_service.proto'
)
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x13sobel_service.proto\x12\x05sobel\"k\n\x0cImageRequest\x12\r\n\x05width\x18\x01 \x01(\x05\x12\x0e\n\x06height\x18\x02 \x01(\x05\x12\x12\n\nimage_data\x18\x03 \x01(\x0c\x12\x12\n\nrequest_id\x18\x04 \x01(\t\x12\x14\n\x0ctimestamp_ms\x18\x05 \x01(\x03\"\xa3\x01\n\rImageResponse\x12\r\n\x05width\x18\x01 \x01(\x05\x12\x0e\n\x06height\x18\x02 \x01(\x05\x12\x13\n\x0bresult_data\x18\x03 \x01(\x0c\x12\x12\n\nrequest_id\x18\x04 \x01(\t\x12\x1b\n\x13server_timestamp_ms\x18\x05 \x01(\x03\x12\x1a\n\x12processing_time_ms\x18\x06 \x01(\x01\x12\x11\n\tserver_id\x18\x07 \x01(\t\"\"\n\rHealthRequest\x12\x11\n\tclient_id\x18\x01 \x01(\t\"Z\n\x0eHealthResponse\x12\x0f\n\x07healthy\x18\x01 \x01(\x08\x12\x11\n\tserver_id\x18\x02 \x01(\t\x12\x0c\n\x04load\x18\x03 \x01(\x05\x12\x16\n\x0euptime_seconds\x18\x04 \x01(\x03\"#\n\x0eMetricsRequest\x12\x11\n\tclient_id\x18\x01 \x01(\t\"\xea\x01\n\x0fMetricsResponse\x12\x11\n\tserver_id\x18\x01 \x01(\t\x12\x16\n\x0etotal_requests\x18\x02 \x01(\x03\x12\x1b\n\x13successful_requests\x18\x03 \x01(\x03\x12\x17\n\x0f\x66\x61iled_requests\x18\x04 \x01(\x03\x12\x1e\n\x16\x61vg_processing_time_ms\x18\x05 \x01(\x01\x12\x1e\n\x16p95_processing_time_ms\x18\x06 \x01(\x01\x12\x1e\n\x16p99_processing_time_ms\x18\x07 \x01(\x01\x12\x16\n\x0euptime_seconds\x18\x08 \x01(\x03\x32\xc8\x01\n\x0cSobelService\x12;\n\x0cProcessImage\x12\x13.sobel.ImageRequest\x1a\x14.sobel.ImageResponse\"\x00\x12<\n\x0bHealthCheck\x12\x14.sobel.HealthRequest\x1a\x15.sobel.HealthResponse\"\x00\x12=\n\nGetMetrics\x12\x15.sobel.MetricsRequest\x1a\x16.sobel.MetricsResponse\"\x00\x62\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'sobel_service_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
  DESCRIPTOR._loaded_options = None
  _globals['_IMAGEREQUEST']._serialized_start=30
  _globals['_IMAGEREQUEST']._serialized_end=137
  _globals['_IMAGERESPONSE']._serialized_start=140
  _globals['_IMAGERESPONSE']._serialized_end=303
  _globals['_HEALTHREQUEST']._serialized_start=305
  _globals['_HEALTHREQUEST']._serialized_end=339
  _globals['_HEALTHRESPONSE']._serialized_start=341
  _globals['_HEALTHRESPONSE']._serialized_end=431
  _globals['_METRICSREQUEST']._serialized_start=433
  _globals['_METRICSREQUEST']._serialized_end=468
  _globals['_METRICSRESPONSE']._serialized_start=471
  _globals['_METRICSRESPONSE']._serialized_end=705
  _globals['_SOBELSERVICE']._serialized_start=708
  _globals['_SOBELSERVICE']._serialized_end=908
# @@protoc_insertion_point(module_scope)
