# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
"""Client and server classes corresponding to protobuf-defined services."""
import grpc
import warnings

import sobel_service_pb2 as sobel__service__pb2

GRPC_GENERATED_VERSION = '1.76.0'
GRPC_VERSION = grpc.__version__
_version_not_supported = False

try:
    from grpc._utilities import first_version_is_lower
    _version_not_supported = first_version_is_lower(GRPC_VERSION, GRPC_GENERATED_VERSION)
except ImportError:
    _version_not_supported = True

if _version_not_supported:
    raise RuntimeError(
        f'The grpc package installed is at version {GRPC_VERSION},'
        + ' but the generated code in sobel_service_pb2_grpc.py depends on'
        + f' grpcio>={GRPC_GENERATED_VERSION}.'
        + f' Please upgrade your grpc module to grpcio>={GRPC_GENERATED_VERSION}'
        + f' or downgrade your generated code using grpcio-tools<={GRPC_VERSION}.'
    )


class SobelServiceStub(object):
    """Sobel Edge Detection Service
    """

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.ProcessImage = channel.unary_unary(
                '/sobel.SobelService/ProcessImage',
                request_serializer=sobel__service__pb2.ImageRequest.SerializeToString,
                response_deserializer=sobel__service__pb2.ImageResponse.FromString,
                _registered_method=True)
        self.HealthCheck = channel.unary_unary(
                '/sobel.SobelService/HealthCheck',
                request_serializer=sobel__service__pb2.HealthRequest.SerializeToString,
                response_deserializer=sobel__service__pb2.HealthResponse.FromString,
                _registered_method=True)
        self.GetMetrics = channel.unary_unary(
                '/sobel.SobelService/GetMetrics',
                request_serializer=sobel__service__pb2.MetricsRequest.SerializeToString,
                response_deserializer=sobel__service__pb2.MetricsResponse.FromString,
                _registered_method=True)


class SobelServiceServicer(object):
    """Sobel Edge Detection Service
    """

    def ProcessImage(self, request, context):
        """Process a single image with Sobel edge detection
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def HealthCheck(self, request, context):
        """Health check for load balancing
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def GetMetrics(self, request, context):
        """Get server metrics
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')


def add_SobelServiceServicer_to_server(servicer, server):
    rpc_method_handlers = {
            'ProcessImage': grpc.unary_unary_rpc_method_handler(
                    servicer.ProcessImage,
                    request_deserializer=sobel__service__pb2.ImageRequest.FromString,
                    response_serializer=sobel__service__pb2.ImageResponse.SerializeToString,
            ),
            'HealthCheck': grpc.unary_unary_rpc_method_handler(
                    servicer.HealthCheck,
                    request_deserializer=sobel__service__pb2.HealthRequest.FromString,
                    response_serializer=sobel__service__pb2.HealthResponse.SerializeToString,
            ),
            'GetMetrics': grpc.unary_unary_rpc_method_handler(
                    servicer.GetMetrics,
                    request_deserializer=sobel__service__pb2.MetricsRequest.FromString,
                    response_serializer=sobel__service__pb2.MetricsResponse.SerializeToString,
            ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
            'sobel.SobelService', rpc_method_handlers)
    server.add_generic_rpc_handlers((generic_handler,))
    server.add_registered_method_handlers('sobel.SobelService', rpc_method_handlers)


 # This class is part of an EXPERIMENTAL API.
class SobelService(object):
    """Sobel Edge Detection Service
    """

    @staticmethod
    def ProcessImage(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/sobel.SobelService/ProcessImage',
            sobel__service__pb2.ImageRequest.SerializeToString,
            sobel__service__pb2.ImageResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def HealthCheck(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/sobel.SobelService/HealthCheck',
            sobel__service__pb2.HealthRequest.SerializeToString,
            sobel__service__pb2.HealthResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def GetMetrics(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/sobel.SobelService/GetMetrics',
            sobel__service__pb2.MetricsRequest.SerializeToString,
            sobel__service__pb2.MetricsResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)
